export default {
    editor: {
        title: "Titel der Karte",
        main_sensors: "Haupt-Sensoren",
        soc: "SoC (Batteriestand %)",
        power: "Gesamtleistung (Watt)",
        voltage: "Batterie Gesamtspannung (Volt)",
        current: "Batterie Gesamtstrom (Ampere)",
        drift: "Zelldrift Externer Sensor (Delta mV)",
        temp: "Batterie Temp (°C)",
        display_options: "Darstellung & Optionen",
        min_voltage: "Minimale Spannung (V)",
        max_voltage: "Maximale Spannung (V)",
        show_header_values: "Werte über Icons anzeigen (Header)",
        hide_bars: "Balkendiagramme ausblenden (Kompaktmodus)",
        horizontal_layout: "Horizontales Layout (Listenansicht)",
        show_as_table: "Als Tabelle anzeigen (Keine Balken)",
        thick_borders: "Dickere Balken-Ränder (2px)",
        enable_animations: "Animationen aktivieren",
        show_cell_voltages: "Spannungswerte anzeigen",
        show_min_max: "Min/Max Zellen markieren",
        show_average: "Durchschnitt anzeigen",
        calc_drift: "Zelldrift (Max-Min) intern berechnen",
        cells: "Zellen",
        add_cell: "Zelle hinzufügen",
        cell_name: "Name",
        cell_entity: "Spannung Sensor",
        cell_balance_entity: "Balancer Sensor (opt.)", // NEU
        cell_background_color: "Hintergrund-Farbe Zellbalken: 'gradient' oder Hex-Farbe",
        cell_background_opacity: "Hintergrund-Deckkraft (0.0 - 1.0)",
        cell_bar_color: "Balkenfarbe-Modus ('range', 'delta' oder Farbe)",
        cell_bar_opacity: "Balken-Deckkraft (0.0 - 1.0)",
        cell_bar_top_color: "Balkenoberfarbe (Hex, für delta-Modus)",
        cell_bar_bottom_color: "Balkenunterfarbe (Hex, für delta-Modus)",

        // Detailansicht Optionen
        show_detailed_view: "Detailansicht aktivieren",
        show_cell_list: "Liste der Einzelzellen anzeigen", 
        show_standard_in_detail: "Standardansicht (Balken) unten anzeigen",
        detailed_sensors: "Detailansicht Sensoren (optional)",
        soh: "SoH (Gesundheit %)",
        capacity: "Kapazität (Ah)",
        cycle_capacity: "Zyklus Kapazität (Ah)",
        cycles: "Ladezyklen",
        temp_mos: "MOS Temp (°C)",
        show_charts: "Charts anzeigen",
        
        stat_charge: "Laden (Switch/Input Boolean/Select)",
        stat_discharge: "Entladen (Switch/Input Boolean/Select)",
        stat_balance: "Balancing Global (Switch/Input Boolean/Select)",
        
        // Custom Values
        val_on: "Wert für ON (z.B. 'Ein' oder 'True')",
        val_off: "Wert für OFF (z.B. 'Aus' oder 'False')"
    },
    card: {
        power: "Leistung",
        soc: "SoC",
        temp: "Temp",
        drift: "Drift",
        avg_cell: "Ø Zelle",

        // Detailansicht Labels
        batt_voltage: "Batterie Spannung",
        delta_cell_vol: "Zell-Differenz",
        max_cell: "Max Zelle",
        charge: "Laden",
        discharge: "Entladen",
        balance: "Balance",
        on: "AN",
        off: "AUS",
        soh: "SoH",
        batt_capacity: "Kapazität",
        cycle_capacity: "Zyklus Kapazität",
        cycle_count: "Zyklen",
        mos_temp: "MOS Temp.",
        min_temp: "Min Temp.",
        max_temp: "Max Temp.",
        remain_capacity: "Restkapazität"
    }
};
